# Generated by Django 6.1 on 2026-08-31 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trialapp', '0002_remove_player_age_remove_player_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPerGameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('team', models.CharField(blank=True, max_length=50)),
                ('pos', models.CharField(blank=True, max_length=20)),
                ('g', models.IntegerField(blank=True, null=True)),
                ('gs', models.IntegerField(blank=True, null=True)),
                ('mp_per_game', models.FloatField(blank=True, null=True)),
                ('fg_per_game', models.FloatField(blank=True, null=True)),
                ('fga_per_game', models.FloatField(blank=True, null=True)),
                ('fg_percent', models.FloatField(blank=True, null=True)),
                ('x3p_per_game', models.FloatField(blank=True, null=True)),
                ('x3pa_per_game', models.FloatField(blank=True, null=True)),
                ('x3p_percent', models.FloatField(blank=True, null=True)),
                ('x2p_per_game', models.FloatField(blank=True, null=True)),
                ('x2pa_per_game', models.FloatField(blank=True, null=True)),
                ('x2p_percent', models.FloatField(blank=True, null=True)),
                ('ft_per_game', models.FloatField(blank=True, null=True)),
                ('fta_per_game', models.FloatField(blank=True, null=True)),
                ('ft_percent', models.FloatField(blank=True, null=True)),
                ('orb_per_game', models.FloatField(blank=True, null=True)),
                ('drb_per_game', models.FloatField(blank=True, null=True)),
                ('trb_per_game', models.FloatField(blank=True, null=True)),
                ('ast_per_game', models.FloatField(blank=True, null=True)),
                ('stl_per_game', models.FloatField(blank=True, null=True)),
                ('blk_per_game', models.FloatField(blank=True, null=True)),
                ('tov_per_game', models.FloatField(blank=True, null=True)),
                ('pf_per_game', models.FloatField(blank=True, null=True)),
                ('pts_per_game', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_game_stats', to='Trialapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerShootingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('team', models.CharField(blank=True, max_length=50)),
                ('pos', models.CharField(blank=True, max_length=20)),
                ('fg_percent', models.FloatField(blank=True, null=True)),
                ('x3p_percent', models.FloatField(blank=True, null=True)),
                ('x2p_percent', models.FloatField(blank=True, null=True)),
                ('e_fg_percent', models.FloatField(blank=True, null=True)),
                ('ft_percent', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shooting_stats', to='Trialapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTotalsStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('team', models.CharField(blank=True, max_length=50)),
                ('pos', models.CharField(blank=True, max_length=20)),
                ('g', models.IntegerField(blank=True, null=True)),
                ('gs', models.IntegerField(blank=True, null=True)),
                ('mp', models.FloatField(blank=True, null=True)),
                ('fg', models.FloatField(blank=True, null=True)),
                ('fga', models.FloatField(blank=True, null=True)),
                ('fg_percent', models.FloatField(blank=True, null=True)),
                ('x3p', models.FloatField(blank=True, null=True)),
                ('x3pa', models.FloatField(blank=True, null=True)),
                ('x3p_percent', models.FloatField(blank=True, null=True)),
                ('x2p', models.FloatField(blank=True, null=True)),
                ('x2pa', models.FloatField(blank=True, null=True)),
                ('x2p_percent', models.FloatField(blank=True, null=True)),
                ('ft', models.FloatField(blank=True, null=True)),
                ('fta', models.FloatField(blank=True, null=True)),
                ('ft_percent', models.FloatField(blank=True, null=True)),
                ('orb', models.FloatField(blank=True, null=True)),
                ('drb', models.FloatField(blank=True, null=True)),
                ('trb', models.FloatField(blank=True, null=True)),
                ('ast', models.FloatField(blank=True, null=True)),
                ('stl', models.FloatField(blank=True, null=True)),
                ('blk', models.FloatField(blank=True, null=True)),
                ('tov', models.FloatField(blank=True, null=True)),
                ('pf', models.FloatField(blank=True, null=True)),
                ('pts', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totals_stats', to='Trialapp.player')),
            ],
        ),
    ]
