# Generated by Django 6.1 on 2026-09-21 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trialapp', '0003_playerpergamestat_playershootingstat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAwardShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('award', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('first', models.IntegerField(blank=True, null=True)),
                ('pts_won', models.FloatField(blank=True, null=True)),
                ('pts_max', models.FloatField(blank=True, null=True)),
                ('share', models.FloatField(blank=True, null=True)),
                ('winner', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_shares', to='Trialapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDraftHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('lg', models.CharField(blank=True, max_length=20)),
                ('overall_pick', models.IntegerField(blank=True, null=True)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('team', models.CharField(blank=True, max_length=50)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_history', to='Trialapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerEndOfSeasonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('lg', models.CharField(blank=True, max_length=20)),
                ('team_type', models.CharField(blank=True, max_length=100)),
                ('number_tm', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('pts_won', models.FloatField(blank=True, null=True)),
                ('pts_max', models.FloatField(blank=True, null=True)),
                ('share', models.FloatField(blank=True, null=True)),
                ('first_team_votes', models.FloatField(blank=True, null=True)),
                ('second_team_votes', models.FloatField(blank=True, null=True)),
                ('third_team_votes', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_of_season_teams', to='Trialapp.player')),
            ],
        ),
    ]
