TEAM_CONFIG = {
    'ATL': {'name': 'Atlanta Hawks', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png'},
    'BOS': {'name': 'Boston Celtics', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png'},
    'BRK': {'name': 'Brooklyn Nets', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png'},
    'CHA': {'name': 'Charlotte Hornets', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png'},
    'CHI': {'name': 'Chicago Bulls', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png'},
    'CLE': {'name': 'Cleveland Cavaliers', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png'},
    'DAL': {'name': 'Dallas Mavericks', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png'},
    'DEN': {'name': 'Denver Nuggets', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/den.png'},
    'DET': {'name': 'Detroit Pistons', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/det.png'},
    'GSW': {'name': 'Golden State Warriors', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png'},
    'HOU': {'name': 'Houston Rockets', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png'},
    'IND': {'name': 'Indiana Pacers', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png'},
    'LAC': {'name': 'LA Clippers', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png'},
    'LAL': {'name': 'Los Angeles Lakers', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png'},
    'MEM': {'name': 'Memphis Grizzlies', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png'},
    'MIA': {'name': 'Miami Heat', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png'},
    'MIL': {'name': 'Milwaukee Bucks', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png'},
    'MIN': {'name': 'Minnesota Timberwolves', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/min.png'},
    'NOP': {'name': 'New Orleans Pelicans', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/no.png'},
    'NYK': {'name': 'New York Knicks', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/ny.png'},
    'OKC': {'name': 'Oklahoma City Thunder', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png'},
    'ORL': {'name': 'Orlando Magic', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png'},
    'PHI': {'name': 'Philadelphia 76ers', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png'},
    'PHX': {'name': 'Phoenix Suns', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png'},
    'POR': {'name': 'Portland Trail Blazers', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/por.png'},
    'SAC': {'name': 'Sacramento Kings', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png'},
    'SAS': {'name': 'San Antonio Spurs', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png'},
    'TOR': {'name': 'Toronto Raptors', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png'},
    'UTA': {'name': 'Utah Jazz', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/utah.png'},
    'WAS': {'name': 'Washington Wizards', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/wsh.png'},

    # Historical abbreviations and franchise relocations.
    'AND': {'name': 'Anderson Packers', 'logo': None},
    'BLB': {'name': 'Baltimore Bullets', 'logo': None},
    'BLT': {'name': 'Baltimore Bullets', 'logo': None},
    'BUF': {'name': 'Buffalo Braves', 'logo': None},
    'CAP': {'name': 'Capital Bullets', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/wsh.png'},
    'CHS': {'name': 'Chicago Stags', 'logo': None},
    'CHZ': {'name': 'Chicago Zephyrs', 'logo': None},
    'CIN': {'name': 'Cincinnati Royals', 'logo': None},
    'CLR': {'name': 'Cleveland Rebels', 'logo': None},
    'DTF': {'name': 'Detroit Falcons', 'logo': None},
    'FTW': {'name': 'Fort Wayne Pistons', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/det.png'},
    'INO': {'name': 'Indianapolis Olympians', 'logo': None},
    'KCK': {'name': 'Kansas City Kings', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png'},
    'KCO': {'name': 'Kansas City-Omaha Kings', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png'},
    'MLH': {'name': 'Milwaukee Hawks', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png'},
    'MNL': {'name': 'Minneapolis Lakers', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png'},
    'NOH': {'name': 'New Orleans Hornets', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png'},
    'NOK': {'name': 'New Orleans/Oklahoma City Hornets', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png'},
    'NJN': {'name': 'New Jersey Nets', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png'},
    'NYN': {'name': 'New York Nets', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png'},
    'PHW': {'name': 'Philadelphia Warriors', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png'},
    'PHL': {'name': 'Philadelphia Warriors', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png'},
    'PIT': {'name': 'Pittsburgh Ironmen', 'logo': None},
    'PRO': {'name': 'Providence Steamrollers', 'logo': None},
    'ROC': {'name': 'Rochester Royals', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png'},
    'SFW': {'name': 'San Francisco Warriors', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png'},
    'SDR': {'name': 'San Diego Rockets', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png'},
    'SDN': {'name': 'San Diego Clippers', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png'},
    'SEA': {'name': 'Seattle SuperSonics', 'logo': None},
    'STB': {'name': 'St. Louis Bombers', 'logo': None},
    'STL': {'name': 'St. Louis Hawks', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png'},
    'SYR': {'name': 'Syracuse Nationals', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png'},
    'TRI': {'name': 'Tri-Cities Blackhawks', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png'},
    'VAN': {'name': 'Vancouver Grizzlies', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png'},
    'WSC': {'name': 'Washington Capitols', 'logo': None},
    'WSB': {'name': 'Washington Bullets', 'logo': 'https://a.espncdn.com/i/teamlogos/nba/500/wsh.png'},
    '3TM': {'name': 'Three-Team Total', 'logo': None},
}


def get_team_display(code):
    code = (code or '').strip().upper()
    configured = TEAM_CONFIG.get(code, {})
    return {
        'code': code,
        'name': configured.get('name', code or 'Unknown team'),
        'logo': configured.get('logo'),
    }
