# Generated by Django 6.1 on 2026-08-18 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trialapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='colleges',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='from_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='ht_in_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(default='temp_player', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='pos',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='to_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='wt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('lg', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('team', models.CharField(blank=True, max_length=50)),
                ('pos', models.CharField(blank=True, max_length=20)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='Trialapp.player')),
            ],
        ),
    ]
